### PR TITLE
remove local Kepler impl, add dep for @superset-ui

### PR DESCRIPTION
**Pull request by DiggidyDave**
This still leaves a small change in superset/assets/src/visualizations/presets/MainPreset.js to register the components, but a subsequent change can possibly remove that. For now, I'm decoupling the two things.

### CODE REVIEW

**Comment by DiggidyDave** [comment]
PTAL @khtruong @hongbosong 

Note, I still need to test this somehow. I'll try in devbox.

**Comment by hongbosong** [comment]
seems like the CI kepler is failing: https://travis-ci.org/lyft/incubator-superset/jobs/606059067?utm_medium=notification&utm_source=github_status

**Comment by DiggidyDave** [comment]
yeah, apparently there are tests in there I forgot to remove. whoops.

**Comment by khtruong** [comment]
Did we run into problems and couldn't push this?? :(

**Pull request closed without merging**
