### PR TITLE
Tagged content native component for dashboards

### PR DESCRIPTION
**Pull request by betodealmeida**
Native component for seeing tagged content:

tagged_content

Posting it here because it's a stacked diff depending on https://github.com/apache/incubator-superset/pull/5524. @vylc, @mistercrunch, any thoughts? Should I add a button to switch from the configuration state to the preview? Anything else I should add to the configuration?

### CODE REVIEW

**Comment by betodealmeida** [comment]
Also, should we add a title to the component? Or just use it in conjunction with a `Header` component?

**Comment by vylc** [comment]
@betodealmeida looks good to me. i don't think we need any other controls, seems pretty intuitive on how to edit/configure...less is more!

**Comment by betodealmeida** [comment]
Added buttons to make it better:

buttons

**Comment by mistercrunch** [comment]
I'm guessing the tags are a logical `OR`, and wondering whether there are use cases for logical `AND`. On the CSS side it looks like there's one horizontal line too many at the top in preview mode.

**Pull request closed without merging**
